title: Primo Buscemi
theme: jekyll-theme-minimal
logo: hopper.jpg
show_downloads: false
github.is_project_page: false
github.is_user_page: false
twitter:
  card: summary
site.description: "La mia pagina personale"
site.logo: "https://primobuscemi.github.io/personal_page/hopper.jpg"
site.title: "Pagina personale di Primo Buscemi"
plugins:
  - jekyll-seo-tag
